# Generated by Django 5.0.4 on 2024-05-09 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='Category',
        ),
    ]
